### ISSUE TITLE
Fatal error: require(): Failed opening required '<repo>/www/form.php'

### ISSUE THREAD

**Issue by bigandy** [WP-API/discovery-php#1]
running `php -S 0.0.0.0:9000 www/index.php` I get: 

PHP Fatal error:  require(): Failed opening required '/www/form.php' (include_path='.:') in /www/index.php on line 19

**Comment by rmccue** [comment]
Whoops, sorry about that! Accidentally left the reference to the file in there even after I removed it. Fixed now, thanks for filing the issue! :)
