### ISSUE TITLE
Unsupported SSL request with demo

### ISSUE THREAD

**Issue by JacobDorman** [WP-API/discovery-php#2]
Site is being served by vagrant, but tried there without success and this doesn't sound like a related error anyway.

_Chrome Version 50.0.2638.0 canary (64-bit)_

```
php -S 0.0.0.0:9000 wordpress/index.php
PHP 5.6.17 Development Server started at Thu Feb  4 17:40:31 2016
Listening on http://0.0.0.0:9000
Document root is /workspace/sites/protobox/web/iba/wordpress
Press Ctrl-C to quit.
```

Then any request to https://localhost:9000/ is met with

```
[Thu Feb  4 17:40:42 2016] 127.0.0.1:51663 Invalid request (Unsupported SSL request)
[Thu Feb  4 17:40:42 2016] 127.0.0.1:51665 Invalid request (Unsupported SSL request)
[Thu Feb  4 17:40:42 2016] 127.0.0.1:51667 Invalid request (Unsupported SSL request)
[Thu Feb  4 17:40:42 2016] 127.0.0.1:51669 Invalid request (Unsupported SSL request)
[Thu Feb  4 17:40:42 2016] 127.0.0.1:51671 Invalid request (Unsupported SSL request)
```

> This site can’t be reached
> localhost unexpectedly closed the connection.
> ERR_CONNECTION_CLOSED

**Comment by rmccue** [comment]
This is intentional. The command there runs PHP's internal server on port 9000, which is a HTTP server. You're trying to access port 9000 as HTTPS, which PHP doesn't support, so it's erroring.

Use http://localhost:9000/ instead :)

**Comment by herickwilke** [comment]
If helps someone some day, I was stunned at this error and the error was in my URL. 

Simple changes HTTPS to HTTP.

**Comment by agozietetenta** [comment]
This helped
